<?php

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_type_build().
 */
function commerce_demo_jsonapi_entity_type_build(array &$entity_types) {
    /** @var $entity_types \Drupal\Core\Entity\EntityTypeInterface[] */
    $allowed = [
        'commerce_currency',
        'commerce_store',
        'commerce_product',
        'commerce_product_variation',
        'commerce_product_attribute_value',
        'taxonomy_term',
        'node',
        'file',
      ];
    array_walk($entity_types, function (EntityTypeInterface $entity_type) use ($allowed) {
      $entity_type->set('internal', !in_array($entity_type->id(), $allowed, TRUE));
    });
  }
